### ISSUE TITLE
Report tab not loading on Azure devops server

### ISSUE THREAD

**Issue by danielmertens** [stryker-mutator/azure-devops-mutationreport-publisher#176] opened 2020-10-21 10:27 UTC
I'm attempting to use this plugin on our Azure devops server but the report tab seems to be infinitely loading when I open it.
I have included my Yaml pipeline (Stryker is running with correct output and the file is generated) and some logs from the Chrome Developers Console. This last one seems to contain an error.

### Versions
 - dotnet-stryker: 0.20.0
 - azure-devops-mutationreport-publisher: 0.1.3

### Yaml

```
- task: DotNetCoreCLI@2
    displayName: 'Install dotnet-stryker'
    inputs:
      command: custom
      custom: tool
      arguments: update dotnet-stryker --tool-path $(Agent.ToolsDirectory)

  - task: Powershell@2
    displayName: 'Run mutation test on ${{ parameters.testName}}'
    inputs:
      workingDirectory: ${{ parameters.workingDirectory }}
      targetType: 'inline'
      script: $(Agent.ToolsDirectory)/dotnet-stryker ${{ parameters.strykerCommands}}

  - task: PublishMutationReport@0
    displayName: 'Publish Mutation Test Report'
    inputs:
      reportPattern: '**/mutation-report.html'
```

### Developer console
![image](https://user-images.githubusercontent.com/17334508/96706985-95d9cb00-1397-11eb-9c24-6afc2a094ca7.png)

I can confirm, by using the diagnostic logs, that the html file is found and uploaded by the task.

**Comment by psfinaki** [comment] 2021-02-24 11:23
Hello, I can confirm this - any progress here?

It took me so much effort to get this extension approved for our organization and now it doesn't seem to work :)

**Comment by Mobrockers** [comment] 2021-02-25 08:16
> Hello, I can confirm this - any progress here?
> 
> It took me so much effort to get this extension approved for our organization and now it doesn't seem to work :)

Hi! Sorry you took the effort to get this approved and for the extension to then not work 😢 
Unfortunately between my work on stryker and my day job I can't currently prioritize this extension even though I would like to. I hope you understand.

**Comment by psfinaki** [comment] 2021-02-25 12:52
Thanks for the response. I understand. If I only I knew TypeScript, I would help myself :)

**Comment by Mobrockers** [comment] 2021-02-25 14:48
Don't worry, I don't know typescript either! 😁

**Comment by xakep139** [comment] 2021-04-23 16:55
I believe the root cause of this issue is related with that workaround: https://github.com/microsoft/azure-devops-extension-api/issues/18#issuecomment-573450435
And apparently that undocumented workaround doesn't work anymore. According to the [docs](https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-sdk/#getconfiguration--) `SDK.getConfiguration()` returns a simple dictionary of values.

**Comment by xakep139** [comment] 2021-04-23 17:20
@rouke-broersma, please kindly review PR #363

**Comment by rouke-broersma** [comment] 2021-04-23 17:26
@xakep139 awesome I'll take a look soon :)

**Comment by psfinaki** [comment] 2021-04-28 16:35
Okay, so that error has gone, now we have this:
![image](https://user-images.githubusercontent.com/5451366/116440075-662ce380-a850-11eb-92af-fe795a7ecef7.png)

@xakep139, any ideas?

**Comment by psfinaki** [comment] 2021-04-28 16:36
@rouke-broersma, I guess I don't have rights to reopen :(

**Comment by rouke-broersma** [comment] 2021-04-28 16:51
> Okay, so that error has gone, now we have this:
> ![image](https://user-images.githubusercontent.com/5451366/116440075-662ce380-a850-11eb-92af-fe795a7ecef7.png)
> 
> @xakep139, any ideas?

We don't use the unpkg package at runtime, there's no reason for that error to be here 🤔

**Comment by nicojs** [comment] 2021-04-29 06:25
Yes, we use `localStorage` to determine the preferred theme here:

https://github.com/stryker-mutator/mutation-testing-elements/blob/bfb565416d48dcaa9c2e2e611d7a53ab4c387107/packages/mutation-testing-elements/src/components/mutation-test-report-app/mutation-test-report-app.component.ts#L75-L86

As a workaround, you can set the `theme` attribute as explained in the readme: https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/mutation-testing-elements#api-reference

I've opened https://github.com/stryker-mutator/mutation-testing-elements/issues/1064 to fix this.

**Comment by psfinaki** [comment] 2021-04-29 09:39
Okay so update here - my latest issue was because of disabled cookies in the browser 🤦 
After I enabled them, the mutation report is shown! 

So given that the other issue is open, this can be probably closed again :)

**Comment by xakep139** [comment] 2021-04-29 09:49
@psfinaki, glad to hear that 😅
@rouke-broersma, thank you for your time and assistance on solving this issue!
Seems like I can't close the issue, so please do it by yourself

**Comment by rouke-broersma** [comment] 2021-04-29 09:56
Thank you guys for putting in the effort, makes it a lot easier for me to do the same!

**Closed by rouke-broersma** 2021-04-29 09:56 UTC
